[project]
name = "auth"
version = "0.1.0"
description = ""
authors = [
    { name = "georgiiviktorov", email = "nowayisleft@gmail.com" }
]

packeges = [
    { include = "auth", from = "src" }
]

requires-python = ">=3.14"
dependencies = [
    "cryptography (>=49.0.0,<50.0.0)"
]

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
